
name: submit-url-youtube-to-podcast-rss

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      URL:
        description: 'YouTube Channel URL'
        type: enviroment
        required: true

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Download ffmpeg for Linux

      run:  |
          sudo apt update
          sudo apt install ffmpeg

    - name: Install dependencies
      run: |
        sudo apt-get update      
        python -m pip install --upgrade pip
        pip install -r dev.txt
    - name: run demo
      run: |
        python feed.py
      env:
        URL: ${{ github.event.inputs.URL }}        
    # 配置git
    - name: Config git
      run: |
        git config --local user.email "ations@github.com"
        git config --local user.name "github"
        git remote set-url origin "https://${{ github.actor }}:${{ github.token }}@github.com/${{ github.repository }}"
    # 更新仓库
    - name: Update repo
      run: |
        git add .
        git commit -m "auto update upwork"
        git pull
        git push -u origin main
      
